backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: 'docs' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Docs' # Used in the UI, ie.: "New Post"
    label_singular: 'Doc'
    folder: 'src/pages/docs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Sidebar Label',
          name: 'sidebar_label',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'category',
          required: true,
        }
      - {
          label: 'Sub-Category',
          name: 'subcategory',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Position',
          name: 'position',
          widget: 'number',
          required: false,
        }
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Blog Post'
    folder: 'src/pages/blog'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Alex Anderson',
        }
      - {
          label: 'Author Link',
          name: 'authorURL',
          widget: 'string',
          default: 'http://twitter.com/ralex1993',
          required: false,
        }
      - {
          label: 'Author Facebook ID (For Profile Picture)',
          name: 'authorFBID',
          widget: 'number',
          default: 764853781,
          required: false,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
  - name: 'simulators'
    label: 'Simulators'
    label_singular: 'Simulator'
    folder: 'src/pages/api/simulators'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Download URL', name: 'url', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'missions'
    label: 'Missions'
    label_singular: 'Mission'
    folder: 'src/pages/api/missions'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Download URL', name: 'url', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
